language: php

php:
  - 5.4

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - php vendor/bin/phpcs --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=build/config/phpcs.xml --ignore=*.html.php,*.config.php,*.twig.php src
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text

after_script:
  - php travis/checkstyle.php

notifications:
  on_success: always
  on_failure: always
