language: php

php:
  - 5.4

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  # - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar

script:
  # - output=$(php -n php-cs-fixer.phar fix -v --dry-run --level=all src); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
  - php vendor/bin/phpcs --report=checkstyle --report-file=build/logs/checkstyle.xml --standard=build/config/phpcs.xml --ignore=*.html.php,*.config.php,*.twig.php src
  - php vendor/bin/phpmd src xml build/config/phpmd.xml --reportfile build/logs/pmd.xml
  - vendor/bin/phpunit --configuration phpunit.yii.xml
  - php travis/junit.php
  - vendor/bin/phpunit --configuration phpunit.laravel.xml
  - php travis/junit.php

after_script:
  - php travis/checkstyle.php
  - php travis/pmd.php

notifications:
  on_success: always
  on_failure: always
