language: php

php:
  - 5.4

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cd tests

script: phpunit ./

notifications:
  on_success: always
  on_failure: always
